package com.echo.rxstructurecache.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "CACHE".
 */
public class Cache {

    private Long id;
    private Long cacheId;
    /** Not-null value. */
    private String content;
    private Integer version;

    public Cache() {
    }

    public Cache(Long id) {
        this.id = id;
    }

    public Cache(Long id, Long cacheId, String content, Integer version) {
        this.id = id;
        this.cacheId = cacheId;
        this.content = content;
        this.version = version;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getCacheId() {
        return cacheId;
    }

    public void setCacheId(Long cacheId) {
        this.cacheId = cacheId;
    }

    /** Not-null value. */
    public String getContent() {
        return content;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setContent(String content) {
        this.content = content;
    }

    public Integer getVersion() {
        return version;
    }

    public void setVersion(Integer version) {
        this.version = version;
    }

}
