package com.echo.rxstructurecache.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.echo.rxstructurecache.dao.Cache;

import com.echo.rxstructurecache.dao.CacheDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig cacheDaoConfig;

    private final CacheDao cacheDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        cacheDaoConfig = daoConfigMap.get(CacheDao.class).clone();
        cacheDaoConfig.initIdentityScope(type);

        cacheDao = new CacheDao(cacheDaoConfig, this);

        registerDao(Cache.class, cacheDao);
    }
    
    public void clear() {
        cacheDaoConfig.getIdentityScope().clear();
    }

    public CacheDao getCacheDao() {
        return cacheDao;
    }

}
