package com.echo.fans.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 *
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig fansDaoConfig;

    private final FansDao fansDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        fansDaoConfig = daoConfigMap.get(FansDao.class).clone();
        fansDaoConfig.initIdentityScope(type);

        fansDao = new FansDao(fansDaoConfig, this);

        registerDao(Fans.class, fansDao);
    }

    public void clear() {
        fansDaoConfig.getIdentityScope().clear();
    }

    public FansDao getFansDao() {
        return fansDao;
    }

}
