package com.echo.fans;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "FANS".
 */
public class Fans {

    private Long id;
    private String name;
    /** Not-null value. */
    private String number;

    public Fans() {
    }

    public Fans(Long id) {
        this.id = id;
    }

    public Fans(Long id, String name, String number) {
        this.id = id;
        this.name = name;
        this.number = number;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    /** Not-null value. */
    public String getNumber() {
        return number;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setNumber(String number) {
        this.number = number;
    }

}
